### ISSUE TITLE
Modifier le text en attente de moderation

### ISSUE THREAD

**Issue by amatyas** [amatyas/idlique#18]
http://ideelique.com/deposer-idee/index.php?su=1&shop=7&fc=module&module=marketplace&controller=addproduct

Ou puis-je modifier le texte de cette page? : 
Votre idée est en attente de modération. Vous recevrez un email lorsqu’elle sera mise en vente (48h max). 
En vous connectant à votre compte, vous pourrez suivre les ventes, vos gains ainsi que les avis des clients. 

Je voudrais ajouter qq mots et ajouter une image: celle de la page d'accueil.

**Comment by amatyas** [comment]
Vince j'ai ajouté l'image. Le text tu peux le changer http://ideelique.com/deposer-idee/backoffice/ au traductions modules.

tres important d'aller à /deposer-idee/backoffice/ et non pas /backoffice car la il s'agit d'une traduction deposant

je te laisse faire les modifs de text

**Comment by Vince7474** [comment]
ok c'est done
