### ISSUE TITLE
récupération de l'idée par l'acheteur

### ISSUE THREAD

**Issue by Vince7474** [amatyas/idlique#19]
sur l'email de livraison de l'idée, faut qu'on propose un lien PDF aussi ; on pourra le customiser avec logo etc.
je t'envoie le model du pdf

le .txt actuel, on le garde aussi, tu peux régler les pbm d'affichage de pontuation stp.

**Comment by Vince7474** [comment]
exemple de pdf envoyé

**Comment by amatyas** [comment]
tu peux attacher ici le PDF editable que t'as crée? je vais le mettre dans l'admin ideelique

**Comment by amatyas** [comment]
cette tache est un doublon avec la #22 je crois

**Comment by Vince7474** [comment]
Voici

Date: Fri, 6 Nov 2015 01:10:23 -0800

**Comment by amatyas** [comment]
je ne vois pas l'attachement :)

**Comment by Vince7474** [comment]
[idee achetee3.pdf](https://github.com/amatyas/idlique/files/28756/idee.achetee3.pdf)
[idee achetee 1.docx](https://github.com/amatyas/idlique/files/28755/idee.achetee.1.docx)

**Comment by Vince7474** [comment]
voici

**Comment by amatyas** [comment]
ok je l'ai mis dans l'admin dans le détail de l’idée. On va utiliser ce template Word pour générer le PDF et l'attacher à l'idée avant la validation de l'idée par l'admin

![capture1](https://cloud.githubusercontent.com/assets/4866156/11021272/509a026e-863c-11e5-93fb-346cb51850d9.PNG)
