### ISSUE TITLE
stats vendeurs

### ISSUE THREAD

**Issue by Vince7474** [amatyas/idlique#20]
modifs stats vendeur:

-les chiffres reste a 0 sur le tableau de stats du vendeur dans son compte vendeur
-le nom de l'idée ne s'affiche pas
-faut enlever la colone "acheteur" ( anonyme normalement?)
-orthographe : Commission Ideelique ( commission avec 2 m)
-on rajoute une colone "pmt effectué " avec la date qui apparait?

**Comment by amatyas** [comment]
ok je regle ca

**Comment by amatyas** [comment]
Done
