### ISSUE TITLE
Pb modification email

### ISSUE THREAD

**Issue by amatyas** [amatyas/idlique#21]
j'ai tenté de modifier les emails, j'ai fait une erreur

Il y a un problème pour obtenir les fichiers d'e-mail.
Veuillez vous assurer que les fichiers anglais existent dans le dossier /var/www/vhosts/ideelique.com/ideelique/themes/pt_furnitureshop/modules/marketplace/mails/en/

**Comment by amatyas** [comment]
j'ai modifié les mails directement dans les fichiers mails. 
C'est plus propre je te laisse faire des test et verifier le contenu des mails.

je n'ai pas encore cherche pkoi prestashop n'arrive pas à recuprer les mails dans l'admin mais je mes suis demerdé sans l'admin

**Comment by Vince7474** [comment]
j'ai fait une inscription et un dépot d'idée, je n'ai reçu aucun email...

Date: Fri, 6 Nov 2015 01:08:13 -0800

**Comment by amatyas** [comment]
Mai tu ne reçois pas de mail au moment du dépôt....tu recoit au niveau dun
achat.

A verifier ...je nai pas testé le depot mais uniquement l'achat d'idée

**Comment by Vince7474** [comment]
on ne recevait pas un email qui disait " votre idée est en modération"
et ensuite un autre  " votre idée est en vente" ??

si c'est pas le cas, je vais les créer!

Date: Fri, 6 Nov 2015 06:02:53 -0800

**Comment by amatyas** [comment]
je test le depot ce soir et je te reviens

**Comment by amatyas** [comment]
done les mails m'ont l'air ok

**Comment by Vince7474** [comment]
finalement, est-ce qu'on envoi un email d'inscription ?
email de dépot d'idée?

ou uniquement email notifiant la vente

**Comment by amatyas** [comment]
Oui on envoie. Regarde dans la boite mail info@ideelique.com. les mails
nont pas pu être envoyés vers ton adresse outlook.
Sur mon gmail ca marche bine ...

**Comment by Vince7474** [comment]
probablement une mauvaise config dans le presta

**Comment by amatyas** [comment]
Je ne crois pas. Ca marche pour tous les mails sauf pour ta boite outlook.
Je dois creuser visiblement c'est  ton hotmail qui bloque l'arrivée des
mails.

Je dois trouver pkoi.
