### ISSUE TITLE
Template pdf/word pour le depot/achat idee

### ISSUE THREAD

**Issue by amatyas** [amatyas/idlique#22]

**Comment by amatyas** [comment]
[idee achetee 1.docx](https://github.com/amatyas/idlique/files/20212/idee.achetee.1.docx)

**Comment by amatyas** [comment]
finallement on propose un fichier Word pou pdf?

le contenu est vraiment tres pro. 
Comment ca va marcher?
 C'est le deposant qui rempli ce ficgier ou c'est nous à la moderation que nous remplissons ce fichier?

**Comment by Vince7474** [comment]
Il faut envoyer l'email de l'idée manuellement, on le remplit a la main. Je pense qu'un pdf ca fait mieux...
J'ai testé le générateur de bizplan que je t'ai envoyé, il est tellement bien fait... on pourrait l'ajouter en lien dans l'email de l'idée dès maintenant avant de développer notre propre site?

je travail sur une super idée, on demande un financement, pour ça que j'ai utilisé le bizplan...je te l'enverrai, garde la pour toi stp
