### ISSUE TITLE
Page contact à travailler

### ISSUE THREAD

**Issue by amatyas** [amatyas/idlique#25]
https://ideelique.com/index.php?controller=contact

**Comment by Vince7474** [comment]
dis moi ou je modifie cette page?

Date: Thu, 5 Nov 2015 14:27:17 -0800

**Comment by amatyas** [comment]
je crois que c'est hardcodé le formulaire. je me suis fait un task pour le modifier ce soir.

je gere merci

**Comment by amatyas** [comment]
done
