### ISSUE TITLE
Video presentation Ideelique

### ISSUE THREAD

**Issue by amatyas** [amatyas/idlique#26]
vince as tu acheté la video? si oui n'hesites pas à me l'envoyer pour la mettre sur le site

**Comment by Vince7474** [comment]
Video: 

Est-ce que  tu peux l'acheter et la mettre sur ta boite? 
59$ pour un accès  de création d'1 mois.

Faut créé un doc de suivi des dépenses, j'ai les 4000€ prêt.
Je sais pas comment les mettre dans ta boite, tu me factures si t'es en manque de tréso, sinon je te fait un virement perso.

les accès de la vidéo : 

https://wideo.co/en/login
vince7474@outlook.fr
annecy74

Date: Fri, 6 Nov 2015 01:09:16 -0800
