### ISSUE TITLE
Modifs coquille

### ISSUE THREAD

**Issue by Vince7474** [amatyas/idlique#29]
https://ideelique.com/deposer-idee/index.php?shop=1&l=3&fc=module&module=marketplace&controller=marketplaceaccount

en attenté de moderation => 

en attente de modération

**Comment by Vince7474** [comment]
https://ideelique.com/deposer-idee/index.php?flag=1&fc=module&module=marketplace&controller=productdetails&id=828

tu peux arranger les accents stp uft8

**Comment by amatyas** [comment]
Done
