### ISSUE TITLE
[Footer] Finaliser le textes statiques 

### ISSUE THREAD

**Issue by amatyas** [amatyas/idlique#3]
Nos parrains

```
Parrain 1 - Societe
Parrain 1 - Societe
Parrain 1 - Societe
Parrain 1 - Societe


Conditions d'utilisation
Règles de confidentialité
Questions fréquentes
Nos engagements
Presse
```

**Comment by Vince7474** [comment]
chérif t'avais pas envoyé les condition d'utilisation, regle de confidentialité? tu peux faire les qst fréquente et nos engagements? je m'occupe de cond d'util et regle de confidentialité

**Comment by amatyas** [comment]
ok on split en 2. les pages sont editables dans le CMS prestashop il me semble

**Comment by amatyas** [comment]
et le footer est editable dans le module statique ....attention on doit faire la config 2 fois ... sur la boutique deposant et sur la boutique acheteur

**Comment by Vince7474** [comment]
ok, fini les règles de confidentialité, tu peux me donner les accèsau back office stp

**Comment by amatyas** [comment]
ideelique.com/backoffice

contact@ideelique.com
ideelique2015+

**Comment by Vince7474** [comment]
je pense qu'on peut enlever pour le moment " les entrepreneurs nous aimes" ainsi que les parrains dans le footer... on remplace les entrepreneurs et parrains par la liste des associations qui financent: on mets le logo, une phrase et un lien vers leur site... On ne parlera pas de partenariat, mais on indique juste que ces associations existent; comme ça on ne pourra rien nous reprocher :)  t'en dis quoi?

**Comment by amatyas** [comment]
Pas de pb...de tte façon on n'a pas bcp de choix :))

**Comment by Vince7474** [comment]
ok tout est fini, j'ai viré "nos engagements" ne sachant pas quoi dire et j'ai repasser en long et large la FAQ, mais tout est deja très bien écrit dans l'explication de chaque section...
