### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by Vince7474** [amatyas/idlique#32]
tu peux ajouter ce tag de tracking du depot d'idée stp

<script type="text/javascript">
/ <![CDATA[ /
var google_conversion_id = 967502078;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "ZQoiCI7o12EQ_tGrzQM";
var google_remarketing_only = false;
/ ]]> /
</script>

<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>

<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/967502078/?label=ZQoiCI7o12EQ_tGrzQM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

**Comment by Vince7474** [comment]
<script type="text/javascript">
/ <![CDATA[ /
var google_conversion_id = 967502078;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "ZQoiCI7o12EQ_tGrzQM";
var google_remarketing_only = false;
/ ]]> /
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/967502078/?label=ZQoiCI7o12EQ_tGrzQM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

**Comment by amatyas** [comment]
le tag est ajouté pour le depot de l'idee
