### ISSUE TITLE
ajout bouton skype "appelez-nous"

### ISSUE THREAD

**Issue by Vince7474** [amatyas/idlique#34]
<script type="text/javascript" src="http://www.skypeassets.com/i/scom/js/skype-uri.js"></script>

<div id="SkypeButton_Call_ideelique_1">
 <script type="text/javascript">
 Skype.ui({
 "name": "dropdown",
 "element": "SkypeButton_Call_ideelique_1",
 "participants": ["ideelique"]
 });
 </script>
</div>

**Comment by amatyas** [comment]
fait
