### ISSUE TITLE
Urgent: ajouter le pixel FB sur toutes les pages, moi je track les dépot et achat

### ISSUE THREAD

**Issue by Vince7474** [amatyas/idlique#35]
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','//connect.facebook.net/en_US/fbevents.js');

fbq('init', '1507529489569315');
fbq('track', "PageView");</script>

<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1507529489569315&ev=PageView&noscript=1"
/></noscript>

**Comment by amatyas** [comment]
FAit
