### ISSUE TITLE
3 emails a créer

### ISSUE THREAD

**Issue by Vince7474** [amatyas/idlique#38]
[email ideelique.docx](https://github.com/amatyas/idlique/files/69538/email.ideelique.docx)

**Comment by amatyas** [comment]
j'ai cree 2/3 mails. Dans l'admin dans le detail de l'idee j'ai mis 2 liens pour envoyer les mails. Attention : 1 simple click et le mail est envoyé. Ideelique est toujours en copie du mail.
![capture](https://cloud.githubusercontent.com/assets/4866156/12011297/2db212ac-acc8-11e5-9dd2-83332129b84b.PNG)

**Comment by Vince7474** [comment]
super :)

Date: Sun, 27 Dec 2015 09:32:29 -0800

**Comment by amatyas** [comment]
3eme mail fait.
