### ISSUE TITLE
Ajouter les tags Google Adwords 

### ISSUE THREAD

**Issue by amatyas** [amatyas/idlique#5]

**Comment by Vince7474** [comment]
je t'envoi les tags

**Comment by Vince7474** [comment]
t'as reçu l'invitation sur le compte adword d'ideelique?

**Comment by amatyas** [comment]
quel compte?

**Comment by amatyas** [comment]
quel mail

**Comment by Vince7474** [comment]
est-ce que je créé un compte adword au nom de ta société?? ( Mab Tech)

Date: Thu, 15 Oct 2015 06:36:33 -0700

**Comment by Vince7474** [comment]
Tu peux créer le compte adword stp,invite moi :
vince7474@outlook.fr
vincent.veyrat.masson@gmail.com

je m'occupe de la création des annonces
