### ISSUE TITLE
thumbs up

### ISSUE THREAD

**Issue by Chiefh** [amatyas/idlique#65]
-mettre le UP a gauche
-virer le  mot "pers." ... ca donnera uniquement l'image + chiffre
-mettre une couleur a chaque pouce ( vert-rouge)  sur la page listing.. ou au chiffre du pouce ( en gras)
-Quand on vote: mettre le UP a gauche
-Quand on vote: le curseur doit absolument réagir qd on le place sur le pouce ( là il ne fait rien, on ne sait pas si c'est cliquable..)=> créer 2 bouton, c'est plus jolie.

**Comment by amatyas** [comment]
fait
