### ISSUE TITLE
rendre impossible le vote non loggé

### ISSUE THREAD

**Issue by Chiefh** [amatyas/idlique#66]

**Comment by amatyas** [comment]
Je ne suis pas fan de ca. Pkoi se mettre une contrainte qui limitera le nb
de votes ...surtout que les votes aujourd'hui sont anonymes

**Comment by Chiefh** [comment]
ok, on garde comme ça

**Comment by amatyas** [comment]
Quel est ton objectif pour dire qu'il doit etre loggue le mec?
Le 30 avr. 2016 12:01 PM, "Andrei Matyas" andrei.matyas@gmail.com a
écrit :

> Je ne suis pas fan de ca. Pkoi se mettre une contrainte qui limitera le nb
> de votes ...surtout que les votes aujourd'hui sont anonymes

**Comment by Chiefh** [comment]
constitué une base de clients, c’est la valeur ajouté de tous les sites

mais on peut opter pour une énorme facilité  d’exp utilisateur..

> Le 30 avr. 2016 à 12:07, amatyas notifications@github.com a écrit :
> 
> Quel est ton objectif pour dire qu'il doit etre loggue le mec?
> Le 30 avr. 2016 12:01 PM, "Andrei Matyas" andrei.matyas@gmail.com a
> écrit :
> 
> > Je ne suis pas fan de ca. Pkoi se mettre une contrainte qui limitera le nb
> > de votes ...surtout que les votes aujourd'hui sont anonymes
> > Le 30 avr. 2016 11:57 AM, "Chiefh" notifications@github.com a écrit :
> > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/amatyas/idlique/issues/66
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub https://github.com/amatyas/idlique/issues/66#issuecomment-215950876

Cordialement,

Vincent Veyrat Masson

Team Ideelique

Site web : https://www.ideelique.com https://www.piwao.com/
Facebook : https://www.facebook.com/Ideelique-1050952318258998/

Twitter : https://twitter.com/ideelique

adresse :9 rue Victor Schoelcher, 92160 Anthony

Tél.: 09 77 19 56 44            

Port.: 07 83 34 81 78

Email : info@ideelique.com mailto:aurelie.lorthiois@piwao.com
