### ISSUE TITLE
ajoute chat online

### ISSUE THREAD

**Issue by Chiefh** [amatyas/idlique#77]
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?3OIXRGaKWVgOm7mV3o6LTpT4e4eIqB3z";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>

**Comment by amatyas** [comment]
tu peux me donner le script zopim stp ....t'avais un compte il me semble 

 Pour accéder au code d’incorporation/script du chat en direct

```
D ans le tableau de bord, sélectionnez Paramètres > Widget .
Copiez le script d’incorporation Zopim, comme illustré dans l’exemple ci-dessous. 
```

**Comment by Chiefh** [comment]
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?3OIXRGaKWVgOm7mV3o6LTpT4e4eIqB3z";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>

**Comment by Chiefh** [comment]
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?3OIXRGaKWVgOm7mV3o6LTpT4e4eIqB3z";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>

**Comment by amatyas** [comment]
c'est fait
