### ISSUE TITLE
utile ou pas, je sais pas (notification analitics)

### ISSUE THREAD

**Issue by Chiefh** [amatyas/idlique#86]
La propriété Ideelique reçoit des données de plusieurs noms d'hôtes redondants. En voici certains :

```
ideelique.com
www.ideelique.com
```

Les noms d'hôtes redondants sont comptabilisés comme des lignes distinctes dans les rapports. Par conséquent, les appels transmis à la même page sur votre site à partir de noms d'hôtes différents seront répartis sur plusieurs lignes. Le trafic indiqué vers des pages spécifiques sera dès lors inférieur à la réalité.

Pour éviter ce problème, pensez à configurer une redirection 301 entre deux de vos noms d'hôtes redondants. Vous pouvez également utiliser un filtre "Rechercher et remplacer" pour supprimer l'élément "www." dans les noms d'hôtes.

Google Tag Assistant Recordings vous permet de vérifier si votre redirection est correctement configurée ou si votre filtre fonctionne comme prévu.

**Comment by amatyas** [comment]
ok c'est reglé ...le WWWet redirectioné sans WWW
